Fix subtitle merge of empty caption
This fix the error: 
AttributeError: 'NoneType' object has no attribute 'start'

Explaining the error:
It is caused because the caption has a blank value, a blank caption with no text, this causes the default code that joins the subtitles to go into error, as it cannot join a received None value, with an existing String value, and ends up breaking the subtitle conversion.

Problem example (DFXP/SMPTE xml):
```<p region='pop1' style='basic' begin='01:55:05:08' end='01:55:11:14' tts:origin='17.5% 84.66%' tts:extent='62.5% 5.33%'>Subtitle End</p>
<p region='pop2' style='basic' begin='01:55:05:08' end='01:55:11:14' tts:origin='50% 84.66%' tts:extent='0% 5.33%'></p>```