Do not use u'' strings in __all__
They are not allowed in __all__ because in Python 2, names are strings,
not unicode vals.

Fixes:

    TypeError: Item in ``from list'' not a string

Signed-off-by: Derek Buitenhuis <derek.buitenhuis@gmail.com>